### PR TITLE
updated  iceland database

### PR DESCRIPTION
**Pull request by pranjalsingh03**
added database of iceland country

### CODE REVIEW

**Comment by Boanerges1996** [comment]
@pranjalsingh03 please fill the district and cities data

**Comment by pranjalsingh03** [comment]
> @pranjalsingh03 please fill the district and cities data

Ok sorry for the inconvenience

**Comment by RamanSharma100** [comment]
@pranjalsingh03 JSON data is having an error please make sure if JSON is correct

**Review by Boanerges1996 — CHANGES_REQUESTED** [review]
Your JSON file is invalid, it also doesn't follow the structure we have provided you.

**Pull request closed without merging**
