### PR TITLE
Issue#65

### PR DESCRIPTION
**Pull request by shubhansu-kr**
Fixed Invalid trailing error in json file.

### CODE REVIEW

**Comment by RakeshPotnuru** [comment]
Don't edit issue templates.

**Comment by shubhansu-kr** [comment]
> Don't edit issue templates.

Reverted the commit.

**Comment by shubhansu-kr** [comment]
@RamanSharma100 Please review the PR

Issue: #[65](https://github.com/gdsclpu/OpenWorldAPI/issues/65)

**Comment by RakeshPotnuru** [comment]
LGTM!

**Pull request merged**
